#!/usr/bin/env bash
#
# Download Paul/hatecheck-{spanish,french,german} from HuggingFace, filter to
# the profanity-relevant functionalities (profanity/slur/spelling-bypass),
# and emit a single JSONL file at bench/data/hatecheck.jsonl.
#
# HateCheck is CC-BY-4.0, so committing the filtered output is OK as long
# as README credits Paul Röttger et al.
#
# Usage: from repo root:
#   bash bench/scripts/convert_hatecheck.sh
set -euo pipefail

WS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${WS_ROOT}/bench/data/hatecheck.jsonl"
TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

# Functionalities that a keyword-based profanity filter can legitimately
# be expected to handle. `profanity_nh` is deliberately excluded — those
# are profane sentences labeled "non-hateful" (because they're not identity-
# based hate), but they still contain profanity, so counting them as FP
# against a profanity filter is a definitional error, not a real mistake.
KEEP_FUNCTIONALITIES=(
    profanity_h
    slur_h
    spell_leet_h
    spell_char_del_h
    spell_char_swap_h
    spell_space_add_h
    spell_space_del_h
)

declare -A LANG_URLS=(
    [es]="https://huggingface.co/datasets/Paul/hatecheck-spanish/resolve/main/test.csv"
    [fr]="https://huggingface.co/datasets/Paul/hatecheck-french/resolve/main/test.csv"
    [de]="https://huggingface.co/datasets/Paul/hatecheck-german/resolve/main/test.csv"
)

echo "# profanite HateCheck slice — generated by bench/scripts/convert_hatecheck.sh" > "${OUT}"
echo "# Source: Paul/hatecheck-{spanish,french,german} (CC-BY-4.0)" >> "${OUT}"
echo "# Kept functionalities: ${KEEP_FUNCTIONALITIES[*]}" >> "${OUT}"

for lang in es fr de; do
    url="${LANG_URLS[$lang]}"
    echo "fetching ${lang}..."
    curl -fsSL "${url}" -o "${TMP}/${lang}.csv"

    python3 - "${TMP}/${lang}.csv" "${lang}" "${OUT}" <<'PY'
import csv, json, sys
inp, lang, out = sys.argv[1], sys.argv[2], sys.argv[3]
keep = {
    "profanity_h", "slur_h",
    "spell_leet_h", "spell_char_del_h", "spell_char_swap_h",
    "spell_space_add_h", "spell_space_del_h",
}
rows = 0
with open(inp, newline="", encoding="utf-8") as f, open(out, "a", encoding="utf-8") as o:
    reader = csv.DictReader(f)
    for row in reader:
        func = row.get("functionality", "")
        if func not in keep:
            continue
        text = row.get("test_case", "").strip()
        gold = row.get("label_gold", "").strip()
        if not text or gold not in ("hateful", "non-hateful"):
            continue
        # Map: hateful -> profane, non-hateful -> benign.
        label = "profane" if gold == "hateful" else "benign"
        rec = {
            "text": text,
            "label": label,
            "category": func,
            "lang": lang,
        }
        o.write(json.dumps(rec, ensure_ascii=False) + "\n")
        rows += 1
print(f"  [{lang}] kept {rows} cases")
PY
done

echo "wrote $(grep -c '^{' "${OUT}") cases to ${OUT}"
