//! Build script: transpile the LDNOOBW wordlists at `data/ldnoobw/<lang>.txt`
//! into Rust source files (`$OUT_DIR/ldnoobw_<lang>.rs`) that expose a
//! `static WORDS: &[StaticEntry]` for each language.
//!
//! The generated files are `include!`ed from `src/data/<lang>.rs` so the
//! hand-editable per-language modules stay small while the raw list lives
//! in `data/ldnoobw/` where it can be refreshed from upstream.
//!
//! Auto-tiering rule:
//!   - contains a space OR >= 12 chars long      -> strict=true  (unambiguous)
//!   - everything else                           -> strict=false
//!
//! Severity defaults to 2 (moderate). Category defaults to Strong.
//! Integrators who want finer tiers should extend via `add_words`.

use std::env;
use std::fs;
use std::path::PathBuf;

const LANGS: &[&str] = &["en", "es", "hi", "fr", "de"];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    for lang in LANGS {
        let in_path = manifest_dir
            .join("data/ldnoobw")
            .join(format!("{lang}.txt"));
        println!("cargo:rerun-if-changed={}", in_path.display());

        let out_path = out_dir.join(format!("ldnoobw_{lang}.rs"));
        let generated = match fs::read_to_string(&in_path) {
            Ok(text) => render(&text),
            Err(_) => render(""), // missing file -> empty list; don't break builds
        };
        fs::write(&out_path, generated).expect("write generated wordlist");
    }

    println!("cargo:rerun-if-changed=build.rs");
}

fn render(text: &str) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from LDNOOBW. DO NOT EDIT BY HAND.\n\n");
    // The generated file is included inside `mod generated` nested inside
    // `data::<lang>`, so Category/StaticEntry live two levels up.
    out.push_str("use super::super::{Category, StaticEntry};\n\n");
    out.push_str("pub(crate) static WORDS: &[StaticEntry] = &[\n");

    let mut count = 0usize;
    for raw in text.lines() {
        let word = raw.trim();
        if word.is_empty() || word.starts_with('#') {
            continue;
        }
        // Strings are embedded as Rust string literals — escape appropriately.
        let escaped = word.replace('\\', "\\\\").replace('"', "\\\"");
        let strict = word.contains(' ') || word.chars().count() >= 12;
        out.push_str(&format!(
            "    StaticEntry {{ word: \"{escaped}\", category: Category::Strong, severity: 2, strict: {strict} }},\n"
        ));
        count += 1;
    }

    out.push_str("];\n");
    out.push_str(&format!("\n// {count} entries generated.\n"));
    out
}
