[package]
name = "profanite-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Node.js bindings for profanite (napi-rs)"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
profanite-core = { workspace = true, features = ["all-langs"] }
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
