[package]
name = "profanite-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Python bindings for profanite (PyO3)"
publish = false

[lib]
name = "profanite"
crate-type = ["cdylib", "rlib"]

[dependencies]
profanite-core = { workspace = true, features = ["all-langs"] }
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py38"] }
